### ISSUE TITLE
How to make torso move less

### ISSUE THREAD

**Issue by redgetan** [xg-chu/GPAvatar#10]
The rendered output has a lot more torso movement compared to the original driving video. Is there a way to lessen torso movement? or even constrain movement to just the head?

https://github.com/xg-chu/GPAvatar/assets/247795/2e3f1ba5-e353-4c05-af2f-f6d54c00e530

**Comment by xg-chu** [comment]
You can smooth the ‘expression’ in the processed driving data to achieve this goal. If you fix the expression, there will be only head movements.
