### ISSUE TITLE
How to get Euler Angles (Roll, Pitch, and Yaw) of head?

### ISSUE THREAD

**Issue by jessehao123** [xg-chu/GPAvatar#12]
Hi Chu,

Great work!
When I print the 'pose' as follows, I can see that the Euler Angles (Roll, Pitch, and Yaw) are 0.

'Val: tensor([[ 0.0000,  0.0000,  0.0000,  0.1269,  0.0079, -0.0079]])'

I print this again, Euler Angles (Roll, Pitch, and Yaw) are 0 as well.
From: https://github.com/xg-chu/lightning_track/blob/main/track_video.py, line114
data_result[frame]['emoca_pose']

[-0.         -0.         -0.          0.05681731 -0.00997547  0.0452126 ]
[-0.         -0.         -0.          0.06888346 -0.01059264  0.04863079]

How do I get the Euler Angles (Roll, Pitch, and Yaw) through this "data_result[frame]['emoca_pose']"? Thanks.

Regards,
/Jeff

**Comment by xg-chu** [comment]
I merge the head pose into camera pose, so you can get the Euler angle of heads from the camera pose matrix.
