### ISSUE TITLE
NoneType' object has no attribute 'ray_aabb_intersect' when run demo img and video

### ISSUE THREAD

**Issue by seetimee** [xg-chu/GPAvatar#17]
after step by step follow your guide.cuda12.0,py39

**Comment by seetimee** [comment]
and two package installed not in the readme is pytorch_lightning-2.2.1 and nerfacc

**Comment by xg-chu** [comment]
For that issue, please make sure your nerfacc version is 0.5.3, I will also post a better environment setup guide.

**Comment by xg-chu** [comment]
Updated, please check out the new environment setup guide. 🚀

**Comment by seetimee** [comment]
after I try then AttributeError: 'NoneType' object has no attribute 'ray_aabb_intersect'

**Comment by seetimee** [comment]
follow the updated guide demo

**Comment by seetimee** [comment]
NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.

**Comment by seetimee** [comment]
python inference.py -r ./checkpoints/one_model.ckpt --driver ./demos/drivers/pdriver --input ./demos/examples/real1
Namespace(driver='./demos/drivers/pdriver', input='./demos/examples/real1', resume='./checkpoints/one_model.ckpt', frame_num=150, rotate=0, if_video=False)
TASK:
    MODEL_LIST:                 OneShotAvatar
    BUILD_TIME:                 2023.07.23
MODEL:
    MODEL_NAME:                 OneModel
    ENGINE_NAME:                LightningEngine
CAMERA:
    CAMERA_TYPE:                cubic
DATASET_AUGMENT:
    RESIZE:                     512
    RANGE:                      [0, 1]
    SAMPLE_NUMBER:              2
TRAIN:
    GENERAL:
        MONTE_CARLO:            False
        TRAIN_ITER:             200000
        SHOW_STAT_ITER:         100
        BATCH_SIZE_PER_GPU:     2
        MODEL_DUMP_INTERVAL:    5000
        EXP_STR:                OneModel_VFHQ
        TIME_STR:               Feb01_0116_qhpnt
    OPTIMIZER:
        LR:                     0.0001
    SCHEDULER:
        TYPE:                   MultiStepLR
        DECAY_RATE:             0.2
        DECAY_STEP:             [130000, 160000]
DATASET:
    DATASET_NAME:               VFHQ
    DATASET_LOADER:             MVLightningPoints
    DATASET_PATH:               ./Data/VFHQ/img_lmdb
    RECORDS_PATH:               ./Data/VFHQ/dataset.pkl
    METADATA_PATH:              ./Data/VFHQ/camera.json
    BACKGROUND_VALUE:           0.0
DEVICES:                        [0, 1, 2, 3]
flame_scale:        5.0
focal_length:       12.0
principal_point:    [0.0, 0.0]
libpng warning: iCCP: known incorrect sRGB profile
Total frames: 500
Run with tracked data: ./demos/examples/real1/tracked_result.pth
Tri-Planes built.
NerfAcc: No CUDA toolkit found. NerfAcc will be disabled.
Traceback (most recent call last):
  File "/data2/stephen/GPAvatar/inference.py", line 259, in <module>
    test_engine.run_images(args.input)
  File "/data2/stephen/GPAvatar/inference.py", line 189, in run_images
    val_results = self.model.forward_inference(**batch_data)
  File "/data2/stephen/miniconda3/envs/GPAvatar/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/stephen/GPAvatar/core/model/OneModel/one_model.py", line 160, in forward_inference
    _, gen_fine, params_dict = self.nerf_camera.render(
  File "/data2/stephen/GPAvatar/core/libs/nerf_camera/camera.py", line 101, in two_path_render
    coarse_rays = self.ray_sampling(noise=noise)
  File "/data2/stephen/GPAvatar/core/libs/nerf_camera/camera.py", line 237, in ray_sampling
    ray_start, ray_end, hit = nerfacc.ray_aabb_intersect(
  File "/data2/stephen/miniconda3/envs/GPAvatar/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data2/stephen/miniconda3/envs/GPAvatar/lib/python3.9/site-packages/nerfacc/grid.py", line 43, in ray_aabb_intersect
    t_mins, t_maxs, hits = _C.ray_aabb_intersect(
  File "/data2/stephen/miniconda3/envs/GPAvatar/lib/python3.9/site-packages/nerfacc/cuda/__init__.py", line 13, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'ray_aabb_intersect'

**Comment by seetimee** [comment]
I will try docker to see whether it will work

**Comment by seetimee** [comment]
sorry.After I uninstall nerfacc and then run pip3 install nerfacc==0.5.3 -f https://nerfacc-bucket.s3.us-west-2.amazonaws.com/whl/torch-2.0.0_cu118.html
 The problem has been solved.Thanks for your excellent work
