### ISSUE TITLE
Discrepancies in Driving Video and Output video Lengths

### ISSUE THREAD

**Issue by minmini2** [xg-chu/GPAvatar#18]
Hello, thank you for sharing your excellent work. 
I'm wondering if there's a way to address the issue where the length of the driving video and the output differ?(video mode)
Do you know any reason why this happened?

**Comment by xg-chu** [comment]
This may caused by the fps setting. Please check line 175 of the inference.py and your video.

**Comment by minmini2** [comment]
Thank you :)
I adjusted the speed of videos.

It seems to be working really well, which is very fun and fascinating.
I tried it out myself, I had two questions.

1. When generating an East Asian face, it seems to mix in somewhat with Western features during the inference. Could this be because the internal weights of the model were trained with a relatively small number of East Asian faces in the VFHQ dataset?

2. The facial details are extremely well-preserved, but on the contrary, the overall picture area seems slightly less sharp (like it's shrouded in mist). Could this be a side effect of the process of integrating multiple photos (MTA)?

**Comment by xg-chu** [comment]
Thank you for your attention☺️
For the two questions:
1. I think you're right, but I didn't do statistics on this problem.
2. I think the MTA may not be the main cause of this problem. Inaccurate tracking in the training data and the additional information about the face provided by point feature may be the main reasons. (But I'm not 100% sure)
