### ISSUE TITLE
Please help me figure out why my result are not as good as demo video？

### ISSUE THREAD

**Issue by seetimee** [xg-chu/GPAvatar#19]
https://github.com/xg-chu/GPAvatar/assets/50852027/83b0d31e-626b-46a2-b5bf-8ec7db0f34bd

**Comment by seetimee** [comment]
Does it have to be straight face？

**Comment by minmini2** [comment]
How about trying to input multiple source images ? including side view

**Comment by xg-chu** [comment]
Side views may be helpful.
