### ISSUE TITLE
related the value of points_scale

### ISSUE THREAD

**Issue by wengjincheng** [xg-chu/GPAvatar#22]
Hi, thanks for your great work, I wanna know the value of points_scale that you used to convert Flame head vertex to point clouds, why did you use the value of 5 ?

**Comment by xg-chu** [comment]
Since I reconstruct the avatar in 1-1-1 space, a scale of 5 can welly resize the flame point cloud to the unit space, thereby utilizing the features of the triplane as much as possible.
