### ISSUE TITLE
Training Stage

### ISSUE THREAD

**Issue by Justinfungi** [xg-chu/GPAvatar#25]
In Training stage, is it possible to provide a command for running it

**Comment by xg-chu** [comment]
The training script is: `python train.py --config one --dataset vfhq`, but you may need to prepare the dataset yourself.

**Comment by xg-chu** [comment]
I will update some tips for building dataset later.

**Comment by Justinfungi** [comment]
> The training script is: `python train.py --config one --dataset vfhq`, but you may need to prepare the dataset yourself.

Thx so much
