### ISSUE TITLE
Which flame model to load

### ISSUE THREAD

**Issue by NIRVANALAN** [xg-chu/GPAvatar#26]
Hi, thanks for the wonderful work.

I tried to use the "inference_ready2go.py" while find that it requires a ```generic_model.pkl```. May I ask how to download it?

(GPAvatar):~/Repo/GPAvatar$ python inference_ready2go.py
Traceback (most recent call last):
  File "/mnt/sfs-common/yslan/Repo/GPAvatar/inference_ready2go.py", line 9, in <module>
    model = gpavatar_r2g().cuda()
  File "/mnt/sfs-common/yslan/Repo/GPAvatar/inference_tools/gpavatar.py", line 25, in __init__
    self.flame = flame_lite(n_shape=100, n_exp=50, scale=5.0)                                                                                                                           File "/mnt/sfs-common/yslan/Repo/GPAvatar/inference_tools/libs/flame_lite/flame_lite.py", line 27, in __init__
    with open(os.path.join(self.flame_path, 'generic_model.pkl'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sfs-common/yslan/Repo/GPAvatar/inference_tools/libs/flame_lite/assets/generic_model.pkl'

**Comment by xg-chu** [comment]
Please follow the instructions to build the resources.

**Comment by NIRVANALAN** [comment]
Thanks, it works. Just a follow up question, I see that only the RGB image is saved to ```render_res.jpg```. How to save the depth regarding the output also? 

Looking forward to your reply.

**Comment by NIRVANALAN** [comment]
I have solved it, thanks.
