### ISSUE TITLE
HDTF Dataset Training

### ISSUE THREAD

**Issue by saatvikmah** [xg-chu/GPAvatar#5]
How to train the model on HDTF, the Dataset Loader and Metadata for VFHQ are different from HDTF? What is the final file organization in VFHQ used in training, How to obtain the .pkl and  .json for metadata of HDTF dataset?

**Comment by xg-chu** [comment]
First, you need to extract frames and package them into lmdb.
And then use [this tracker](https://github.com/xg-chu/lightning_track) to obtain annotations for training.
The final step is to use a simple conversion script to get pkl and json, which I will update to this repo soon.

**Comment by huangxin168** [comment]
> First, you need to extract frames and package them into lmdb. And then use [this tracker](https://github.com/xg-chu/lightning_track) to obtain annotations for training. The final step is to use a simple conversion script to get pkl and json, which I will update to this repo soon.

I also want the detailed processes to train a model, do you have plan to release the training code?

**Comment by wengjincheng** [comment]
> First, you need to extract frames and package them into lmdb. And then use [this tracker](https://github.com/xg-chu/lightning_track) to obtain annotations for training. The final step is to use a simple conversion script to get pkl and json, which I will update to this repo soon.

Hi, will you publish the conversion script to this repo?
